name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests with Maven
        run: mvn test

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: target/surefire-reports/*

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-jar
          path: target/*.jar
