name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Run tests with Maven
      run: mvn test

    # XML + TXT reports (surefire-reports folder)
    - name: Upload XML Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: xml-test-reports
        path: target/surefire-reports/*

    # HTML report (site folder)
    - name: Upload HTML Test Report
      uses: actions/upload-artifact@v4
      with:
        name: html-test-report
        path: target/site/surefire-report.html
